'use strict';

/**
 * @ngdoc function
 * @name dozerApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the dozerApp
 */
angular.module('dozerApp')
  .controller('MainController', function ($scope) {
    $scope.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
    $scope.asset = {
		"assetFactory":{},
		"assetFactoryContainer":{},
		"connectorContainer":{},
		"contentType":{},
		"contentTypeContainer":{},
		"dataDefinition":{},
		"dataDefinitionContainer":{},
		"databaseTransport":{},
		"destination":{},
		"facebookConnector":{},
		"feedBlock":{},
		"file":{},
		"fileSystemTransport":{},
		"folder":{},
		"ftpTransport":{},
		"googleAnalyticsConnector":{},
		"group":{},
		"indexBlock":{},
		"metadataSet":{},
		"metadataSetContainer":{},
		"page":{
			"configurationSetId":{},
			"configurationSetPath":{},
			"contentTypeId":"b712a796a9ed4630015f1a42234b34f0",
			"contentTypePath":"FacultyProfile",
			"createdBy":"jasona",
			"createdDate":"2008-10-10T23:07:14.266Z",
			"expirationFolderId":{},
			"expirationFolderPath":{},
			"expirationFolderRecycled":"false",
			"id":"e9038628a9ed4630001644c958be4edb",
			"lastModifiedBy":"jomartin",
			"lastModifiedDate":"2015-02-02T23:51:56.248Z",
			"lastPublishedBy":"chenniga",
			"lastPublishedDate":"2015-03-16T22:12:37.719Z",
			"maintainAbsoluteLinks":"false",
			"metadata":{
				"author":{},
				"displayName":"Vikram Amar",
				"dynamicFields":{
					"dynamicField":
						[
							{
								"fieldValues":{"fieldValue":{"value":{}}},
								"name":"headerTitleOverride"
							},
							{
								"fieldValues":{"fieldValue":{"value":"yes"}},
								"name":"titleVisible"
							},
							{
								"fieldValues":{"fieldValue":{"value":{}}},
								"name":"titleOverride"
							},
							{
								"fieldValues":{"fieldValue":{"value":"no"}},
								"name":"subNavVisible"
							},
							{
								"fieldValues":{"fieldValue":{"value":"yes"}},
								"name":"SubNavDisplay"
							},
							{
								"fieldValues":{"fieldValue":{"value":"2"}},
								"name":"sidebar"
							},
							{
								"fieldValues":{"fieldValue":{"value":"yes"}},
								"name":"googleSiteMap"
							},
							{
								"fieldValues":{"fieldValue":{"value":"0.5"}},
								"name":"googleSitemapPriority"
							},
							{
								"fieldValues":{"fieldValue":{"value":"aspx"}},
								"name":"pageExtension"
							}
						]
					},
				"endDate":{},
				"keywords":{},
				"metaDescription":{},
				"reviewDate":{},
				"startDate":{},
				"summary":{},
				"teaser":{},
				"title":"Vikram Amar"
			},
			"metadataSetId":{},
			"metadataSetPath":{},
			"name":"index",
			"pageConfigurations":{
				"pageConfiguration":{
					"defaultConfiguration":"true",
					"formatId":{},
					"formatPath":{},
					"formatRecycled":"false",
					"id":"b71063eaa9ed4630015f1a420f45e6e9",
					"includeXMLDeclaration":"false",
					"name":"default",
					"outputExtension":{},
					"pageRegions":{
						"pageRegion":
							[
								{
									"blockId":"41e6e024a9ed463001afcf200b28fbdc",
									"blockPath":"_internal/blocks/index_blocks/metadata_block",
									"blockRecycled":"false",
									"formatId":"41f929b8a9ed463001afcf20bf606f52",
									"formatPath":"_internal/formats/thirdlevel/page-title",
									"formatRecycled":"false",
									"id":"a82b100ba9ed4630015f1a42dc44fddc",
									"name":"CONTENT-TITLE",
									"noBlock":"false",
									"noFormat":"false"
								},
								{
									"blockId":{},
									"blockPath":{},
									"blockRecycled":"false",
									"formatId":{},
									"formatPath":{},
									"formatRecycled":"false",
									"id":"a82b100ba9ed4630015f1a42b7649c22",
									"name":"PAGE-SPECIFIC-CSS",
									"noBlock":"false",
									"noFormat":"false"
								},
								{
									"blockId":"09ba13e5a9ed463001a1ee4735f3b040","blockPath":"_internal/blocks/index_blocks/self-metadata","blockRecycled":"false","formatId":"09bfb7f5a9ed463001a1ee4774fb8edc","formatPath":"_internal/formats/template/insertMetadata","formatRecycled":"false","id":"09d93a68a9ed463001a1ee47181dffe4","name":"CASCADE-METADATA","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"e02ca0f9a9ed9fa8216891f0e8f1e06d","blockPath":"_internal/blocks/includes_block/js/includes_faculty","blockRecycled":"false","formatId":{},"formatPath":{},"formatRecycled":"false","id":"e02d29e1a9ed9fa8216891f0aab8f8d0","name":"PAGE-SPECIFIC-JS","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"d08aefc2a9ed9fa80214fe17bf938089","blockPath":"_internal/blocks/index_blocks/nav/primary","blockRecycled":"false","formatId":"d0a83d96a9ed9fa80214fe174327bc0b","formatPath":"_internal/formats/navigation/primary","formatRecycled":"false","id":"bf1de8bba9ed9fa80214fe17a42f9193","name":"NAV-PRIMARY","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"e0339699a9ed9fa8216891f0d47201ff","blockPath":"_internal/blocks/includes_block/js/main","blockRecycled":"false","formatId":{},"formatPath":{},"formatRecycled":"false","id":"a82b100ba9ed4630015f1a424ba2fd8c","name":"INCLUDES-JS","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"bf207d42a9ed9fa80214fe1749b850ac","blockPath":"_internal/blocks/template_blocks/header","blockRecycled":"false","formatId":{},"formatPath":{},"formatRecycled":"false","id":"a82b100ba9ed4630015f1a42ff76592f","name":"HEADER","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"b859ebefa9ed46300082af41da2a8da6","blockPath":"_internal/blocks/index_blocks/hierarchy-metadata","blockRecycled":"false","formatId":"94c51784a9ed46300082af41d2a8cbea","formatPath":"_internal/formats/thirdlevel/header title","formatRecycled":"false","id":"b85c6359a9ed46300082af41547ad56f","name":"HEAD-PAGE-TITLE","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":{},"blockPath":{},"blockRecycled":"false","formatId":"188809bfa9ed463001afcf206d4efed8","formatPath":"_internal/formats/other_stylesheets/no-output","formatRecycled":"false","id":"b711e7fea9ed4630015f1a423a44de10","name":"DEFAULT","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"c42001eba9ed9fa801420a67634521d5","blockPath":"_internal/blocks/index_blocks/self-content","blockRecycled":"false","formatId":"b41dd10ca9ed4630015f1a42e1ab10e5","formatPath":"_internal/formats/other_stylesheets/Faculty Profile Left","formatRecycled":"false","id":"d979a862a9ed9fa8216891f0b158786f","name":"SUBNAV","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"d3fa984ca9ed9fa80214fe17171af1bd","blockPath":"_internal/blocks/index_blocks/Related Links","blockRecycled":"false","formatId":"d3fe61eca9ed9fa80214fe175323e8bd","formatPath":"_internal/formats/navigation/Related Links","formatRecycled":"false","id":"beece470a9ed9fa80214fe17d5d20de7","name":"QUICKLINKS","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":{},"blockPath":{},"blockRecycled":"false","formatId":{},"formatPath":{},"formatRecycled":"false","id":"211c72e9a9ed9fa8216891f0164dcfb7","name":"SIDEBAR-BOTTOM","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"c9409dffa9ed9fa80214fe170304212f","blockPath":"_internal/blocks/includes_block/css/main","blockRecycled":"false","formatId":{},"formatPath":{},"formatRecycled":"false","id":"a82b100ba9ed4630015f1a421d3745ae","name":"INCLUDES-CSS","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"d08aefc2a9ed9fa80214fe17bf938089","blockPath":"_internal/blocks/index_blocks/nav/primary","blockRecycled":"false","formatId":"d3a7d3aba9ed9fa80214fe175936f5d0","formatPath":"_internal/formats/navigation/secondary","formatRecycled":"false","id":"bf1de8bba9ed9fa80214fe17786e0472","name":"NAV-SECONDARY","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":{},"blockPath":{},"blockRecycled":"false","formatId":{},"formatPath":{},"formatRecycled":"false","id":"a82b100ba9ed4630015f1a42604fc7b4","name":"POST-CONTENT","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":{},"blockPath":{},"blockRecycled":"false","formatId":{},"formatPath":{},"formatRecycled":"false","id":"beece470a9ed9fa80214fe1709195db4","name":"DEFAULT-PRE","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"d9767dd3a9ed9fa8216891f01938b4d7","blockPath":"_internal/blocks/index_blocks/Faculty","blockRecycled":"false","formatId":"d978292da9ed9fa8216891f032294d31","formatPath":"_internal/formats/other_stylesheets/Faculty Profile Content","formatRecycled":"false","id":"d979a862a9ed9fa8216891f003d031a6","name":"DEFAULT-POST","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":{},"blockPath":{},"blockRecycled":"false","formatId":{},"formatPath":{},"formatRecycled":"false","id":"bef90304a9ed9fa80214fe1752ac24d1","name":"SPLASH","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"c93f0bc3a9ed9fa80214fe1714c4ef01","blockPath":"_internal/blocks/includes_block/js/Modernizr","blockRecycled":"false","formatId":{},"formatPath":{},"formatRecycled":"false","id":"c93e0c27a9ed9fa80214fe172b959ebc","name":"MODERNIZR","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"18adcb18a9ed463001afcf20a32065c3","blockPath":"_internal/blocks/template_blocks/google-analytics","blockRecycled":"false","formatId":{},"formatPath":{},"formatRecycled":"false","id":"a82b100ba9ed4630015f1a42bb774904","name":"PRE-BODY-CLOSE","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":{},"blockPath":{},"blockRecycled":"false","formatId":{},"formatPath":{},"formatRecycled":"false","id":"211c72e9a9ed9fa8216891f0b1b47868","name":"SIDEBAR-TOP","noBlock":"false","noFormat":"false"
								},
								{
									"blockId":"347d5b3da9ed4630015c5f5e16145d7a","blockPath":"_internal/blocks/template_blocks/footer","blockRecycled":"false","formatId":{},"formatPath":{},"formatRecycled":"false","id":"a82b100ba9ed4630015f1a42a57aa3ba","name":"FOOTER","noBlock":"false","noFormat":"false"
								}
							]
						},
						"publishable":"false",
						"serializationType":{},
						"templateId":"a82b100ba9ed4630015f1a42174a8973",
						"templatePath":"_internal/templates/unified_page_aspx"
					}
				},
				"parentFolderId":"e903856ca9ed4630001644c992d23b01",
				"parentFolderPath":"faculty/amar",
				"path":"faculty/amar/index",
				"shouldBeIndexed":"true",
				"shouldBePublished":"true",
				"siteId":"ba545543a9ed463001f7a5ab63d0a078",
				"siteName":"LawWeb",
				"structuredData":{
					"definitionId":{},
					"definitionPath":{},
					"structuredDataNodes":{
						"structuredDataNode":
							[
								{
									"assetType":{},
									"blockId":{},
									"blockPath":{},
									"fileId":{},
									"filePath":{},
									"identifier":"person",
									"pageId":{},
									"pagePath":{},
									"recycled":"false",
									"structuredDataNodes":{
										"structuredDataNode":
											[
												{
													"assetType":{},
													"blockId":{},
													"blockPath":{},
													"fileId":{},
													"filePath":{},
													"identifier":"name",
													"pageId":{},
													"pagePath":{},
													"recycled":"false",
													"structuredDataNodes":{
														"structuredDataNode":
															[
																{
																	"assetType":{},
																	"blockId":{},
																	"blockPath":{},
																	"fileId":{},
																	"filePath":{},
																	"identifier":"first",
																	"pageId":{},
																	"pagePath":{},
																	"recycled":"false",
																	"structuredDataNodes":{},
																	"symlinkId":{},
																	"symlinkPath":{},
																	"text":"Vikram",
																	"type":"text"
																},
																{
																	"assetType":{},
																	"blockId":{},
																	"blockPath":{},
																	"fileId":{},
																	"filePath":{},
																	"identifier":"middle",
																	"pageId":{},
																	"pagePath":{},
																	"recycled":"false",
																	"structuredDataNodes":{},
																	"symlinkId":{},
																	"symlinkPath":{},
																	"text":{},
																	"type":"text"
																},
																{
																	"assetType":{},
																	"blockId":{},
																	"blockPath":{},
																	"fileId":{},
																	"filePath":{},
																	"identifier":"last",
																	"pageId":{},
																	"pagePath":{},
																	"recycled":"false",
																	"structuredDataNodes":{},
																	"symlinkId":{},
																	"symlinkPath":{},
																	"text":"Amar",
																	"type":"text"
																}
															]
														},
														"symlinkId":{},
														"symlinkPath":{},
														"text":{},
														"type":"group"
													},
													{
														"assetType":{},
														"blockId":{},
														"blockPath":{},
														"fileId":{},
														"filePath":{},
														"identifier":"active",
														"pageId":{},
														"pagePath":{},
														"recycled":"false",
														"structuredDataNodes":{},
														"symlinkId":{},
														"symlinkPath":{},
														"text":"::CONTENT-XML-CHECKBOX::Yes",
														"type":"text"
													},
													{
														"assetType":{},
														"blockId":{},
														"blockPath":{},
														"fileId":{},
														"filePath":{},
														"identifier":"title",
														"pageId":{},
														"pagePath":{},
														"recycled":"false",
														"structuredDataNodes":{},
														"symlinkId":{},
														"symlinkPath":{},
														"text":"Associate Dean for Academic Affairs, Professor of Law",
														"type":"text"
													},
													{
														"assetType":{},
														"blockId":{},
														"blockPath":{},
														"fileId":{},
														"filePath":{},
														"identifier":"status",
														"pageId":{},
														"pagePath":{},"recycled":"false",
														"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
														"text":"Professor","type":"text"
													},
													{
														"assetType":{},"blockId":{},"blockPath":{},
														"fileId":{},"filePath":{},"identifier":"displayOrder",
														"pageId":{},"pagePath":{},"recycled":"false",
														"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
														"text":"2","type":"text"
													},
													{
														"assetType":{},"blockId":{},"blockPath":{},
														"fileId":{},"filePath":{},"identifier":"pidm",
														"pageId":{},"pagePath":{},"recycled":"false",
														"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
														"text":"000000","type":"text"
													},
													{
														"assetType":{},"blockId":{},"blockPath":{},
														"fileId":{},"filePath":{},"identifier":"ssrn",
														"pageId":{},"pagePath":{},"recycled":"false",
														"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
														"text":"57772","type":"text"
													},
													{
														"assetType":{},"blockId":{},"blockPath":{},
														"fileId":{},"filePath":{},"identifier":"linkedin",
														"pageId":{},"pagePath":{},"recycled":"false",
														"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
														"text":{},"type":"text"
													},
													{
														"assetType":{},"blockId":{},"blockPath":{},
														"fileId":{},"filePath":{},"identifier":"numberNewStories",
														"pageId":{},"pagePath":{},"recycled":"false",
														"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
														"text":"20","type":"text"
													},
													{
														"assetType":{},"blockId":{},"blockPath":{},
														"fileId":{},"filePath":{},"identifier":"email",
														"pageId":{},"pagePath":{},"recycled":"false",
														"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
														"text":"vdamar@ucdavis.edu","type":"text"
													},
													{
														"assetType":{},"blockId":{},"blockPath":{},
														"fileId":{},"filePath":{},"identifier":"phone",
														"pageId":{},"pagePath":{},"recycled":"false",
														"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
														"text":"530-752-8808","type":"text"
													},
													{
														"assetType":{},"blockId":{},"blockPath":{},
														"fileId":{},"filePath":{},"identifier":"Office",
														"pageId":{},"pagePath":{},"recycled":"false",
														"structuredDataNodes":{
															"structuredDataNode":
																[
																	{
																		"assetType":{},"blockId":{},"blockPath":{},
																		"fileId":{},"filePath":{},"identifier":"officeNumber",
																		"pageId":{},"pagePath":{},"recycled":"false",
																		"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																		"text":"2102","type":"text"
																	},
																	{
																		"assetType":{},"blockId":{},"blockPath":{},
																		"fileId":{},"filePath":{},"identifier":"building",
																		"pageId":{},"pagePath":{},"recycled":"false",
																		"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																		"text":"King Hall","type":"text"
																	}
																]
															},
															"symlinkId":{},
															"symlinkPath":{},
															"text":{},
															"type":"group"
														},
														{
															"assetType":{},"blockId":{},"blockPath":{},
															"fileId":{},"filePath":{},"identifier":"Wayfinding",
															"pageId":{},"pagePath":{},"recycled":"false",
															"structuredDataNodes":{
																"structuredDataNode":
																	[
																		{
																			"assetType":{},"blockId":{},"blockPath":{},
																			"fileId":{},"filePath":{},"identifier":"wayfindingOfficeNumber",
																			"pageId":{},"pagePath":{},"recycled":"false",
																			"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																			"text":"2102","type":"text"
																		},
																		{
																			"assetType":{},"blockId":{},"blockPath":{},
																			"fileId":{},"filePath":{},"identifier":"wayfindingBuilding",
																			"pageId":{},"pagePath":{},"recycled":"false",
																			"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																			"text":"King Hall","type":"text"
																		}
																	]
																},
																"symlinkId":{},
																"symlinkPath":{},
																"text":{},"type":"group"
															}
														]
													},
													"symlinkId":{},
													"symlinkPath":{},"text":{},"type":"group"
												},
												{
													"assetType":{},"blockId":{},"blockPath":{},
													"fileId":{},"filePath":{},"identifier":"educationalHistory",
													"pageId":{},"pagePath":{},"recycled":"false",
													"structuredDataNodes":{
														"structuredDataNode":
															[
																{
																	"assetType":{},"blockId":{},"blockPath":{},
																	"fileId":{},"filePath":{},"identifier":"education",
																	"pageId":{},"pagePath":{},"recycled":"false",
																	"structuredDataNodes":{
																		"structuredDataNode":
																			[
																				{
																					"assetType":{},"blockId":{},"blockPath":{},
																					"fileId":{},"filePath":{},"identifier":"degree",
																					"pageId":{},"pagePath":{},"recycled":"false",
																					"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																					"text":"J.D.","type":"text"
																				},
																				{
																					"assetType":{},"blockId":{},"blockPath":{},
																					"fileId":{},"filePath":{},"identifier":"honors",
																					"pageId":{},"pagePath":{},"recycled":"false",
																					"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																					"text":{},"type":"text"
																				},
																				{
																					"assetType":{},"blockId":{},"blockPath":{},
																					"fileId":{},"filePath":{},"identifier":"subject",
																					"pageId":{},"pagePath":{},"recycled":"false",
																					"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																					"text":{},"type":"text"
																				},
																				{
																					"assetType":{},"blockId":{},"blockPath":{},
																					"fileId":{},"filePath":{},"identifier":"school",
																					"pageId":{},"pagePath":{},"recycled":"false",
																					"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																					"text":"Yale University","type":"text"
																				},
																				{
																					"assetType":{},"blockId":{},"blockPath":{},
																					"fileId":{},"filePath":{},"identifier":"year",
																					"pageId":{},"pagePath":{},"recycled":"false",
																					"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																					"text":"1988","type":"text"
																				},
																				{
																					"assetType":{},"blockId":{},"blockPath":{},
																					"fileId":{},"filePath":{},"identifier":"societies",
																					"pageId":{},"pagePath":{},"recycled":"false",
																					"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																					"text":{},"type":"text"
																				}
																			]
																		},
																		"symlinkId":{},"symlinkPath":{},
																		"text":{},"type":"group"
																	},
																	{
																		"assetType":{},"blockId":{},"blockPath":{},
																		"fileId":{},"filePath":{},"identifier":"education",
																		"pageId":{},"pagePath":{},"recycled":"false",
																		"structuredDataNodes":{
																			"structuredDataNode":
																				[
																					{
																						"assetType":{},"blockId":{},"blockPath":{},
																						"fileId":{},"filePath":{},"identifier":"degree",
																						"pageId":{},"pagePath":{},"recycled":"false",
																						"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																						"text":"A.B.","type":"text"
																					},
																					{
																						"assetType":{},"blockId":{},"blockPath":{},
																						"fileId":{},"filePath":{},"identifier":"honors",
																						"pageId":{},"pagePath":{},"recycled":"false",
																						"structuredDataNodes":{},
																						"symlinkId":{},"symlinkPath":{},
																						"text":{},"type":"text"
																					},
																					{
																						"assetType":{},"blockId":{},"blockPath":{},
																						"fileId":{},"filePath":{},"identifier":"subject",
																						"pageId":{},"pagePath":{},"recycled":"false",
																						"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																						"text":"History","type":"text"
																					},
																					{
																						"assetType":{},"blockId":{},"blockPath":{},
																						"fileId":{},"filePath":{},"identifier":"school",
																						"pageId":{},"pagePath":{},"recycled":"false",
																						"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																						"text":"University of California at Berkeley","type":"text"
																					},
																					{
																						"assetType":{},"blockId":{},"blockPath":{},
																						"fileId":{},"filePath":{},"identifier":"year",
																						"pageId":{},"pagePath":{},"recycled":"false",
																						"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																						"text":{},"type":"text"
																					},
																					{
																						"assetType":{},"blockId":{},"blockPath":{},
																						"fileId":{},"filePath":{},"identifier":"societies",
																						"pageId":{},"pagePath":{},"recycled":"false",
																						"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																						"text":{},"type":"text"
																					}
																				]
																			},
																			"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
																		}
																	]
																},
																"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
															},
															{
																"assetType":{},"blockId":{},"blockPath":{},
																"fileId":{},"filePath":{},"identifier":"memberships",
																"pageId":{},"pagePath":{},"recycled":"false",
																"structuredDataNodes":{
																	"structuredDataNode":{
																		"assetType":{},"blockId":{},"blockPath":{},
																		"fileId":{},"filePath":{},"identifier":"member",
																		"pageId":{},"pagePath":{},"recycled":"false",
																		"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																		"text":"::CONTENT-XML-CHECKBOX::ALI","type":"text"
																	}
																},
																"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
															},
															{
																"assetType":{},"blockId":{},"blockPath":{},
																"fileId":{},"filePath":{},"identifier":"links",
																"pageId":{},"pagePath":{},"recycled":"false",
																"structuredDataNodes":{
																	"structuredDataNode":
																		[
																			{
																				"assetType":{},"blockId":{},"blockPath":{},
																				"fileId":{},"filePath":{},"identifier":"link",
																				"pageId":{},"pagePath":{},"recycled":"false",
																				"structuredDataNodes":{
																					"structuredDataNode":
																						[
																							{
																								"assetType":{},"blockId":{},"blockPath":{},
																								"fileId":{},"filePath":{},"identifier":"label",
																								"pageId":{},"pagePath":{},"recycled":"false",
																								"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																								"text":"Justia.com articles","type":"text"
																							},
																							{
																								"assetType":{},"blockId":{},"blockPath":{},
																								"fileId":{},"filePath":{},"identifier":"hyperlink",
																								"pageId":{},"pagePath":{},"recycled":"false",
																								"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																								"text":"http://verdict.justia.com/author/amar","type":"text"
																							}
																						]
																					},
																					"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
																				},
																				{
																					"assetType":{},"blockId":{},"blockPath":{},
																					"fileId":{},"filePath":{},"identifier":"link",
																					"pageId":{},"pagePath":{},"recycled":"false",
																					"structuredDataNodes":{
																						"structuredDataNode":
																							[
																								{
																									"assetType":{},"blockId":{},"blockPath":{},
																									"fileId":{},"filePath":{},"identifier":"label",
																									"pageId":{},"pagePath":{},"recycled":"false",
																									"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																									"text":"Findlaw.com articles","type":"text"
																								},
																								{
																									"assetType":{},"blockId":{},"blockPath":{},
																									"fileId":{},"filePath":{},"identifier":"hyperlink",
																									"pageId":{},"pagePath":{},"recycled":"false",
																									"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																									"text":"http://writ.news.findlaw.com/amar/","type":"text"
																								}
																							]
																						},
																						"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
																					}
																				]
																			},
																			"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
																		},
																		{
																			"assetType":{},"blockId":{},"blockPath":{},
																			"fileId":{},"filePath":{},"identifier":"cv",
																			"pageId":{},"pagePath":{},"recycled":"false",
																			"structuredDataNodes":{
																				"structuredDataNode":
																					[
																						{
																							"assetType":"file","blockId":{},
																							"blockPath":{},"fileId":"d6c1d3f8a9ed4630012e49c352b4237c",
																							"filePath":"faculty/amar/files/Amar_CV.pdf",
																							"identifier":"cv","pageId":{},"pagePath":{},"recycled":"false",
																							"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																							"text":{},"type":"asset"
																						},
																						{
																							"assetType":{},"blockId":{},"blockPath":{},
																							"fileId":{},"filePath":{},"identifier":"cvLabel",
																							"pageId":{},"pagePath":{},"recycled":"false",
																							"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																							"text":"Curriculum Vitae","type":"text"
																						}
																					]
																				},
																				"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
																			},
																			{
																				"assetType":{},"blockId":{},"blockPath":{},
																				"fileId":{},"filePath":{},"identifier":"biography",
																				"pageId":{},"pagePath":{},"recycled":"false",
																				"structuredDataNodes":{
																					"structuredDataNode":{
																						"assetType":{},
																						"blockId":{},
																						"blockPath":{},
																						"fileId":{},
																						"filePath":{},"identifier":"biography","pageId":{},"pagePath":{},
																						"recycled":"false","structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																						"text":"<p>Vikram Amar rejoined the UC Davis Law School (where he was a faculty member from 1993-1998) in 2007, after teaching at UC Hastings for a decade. In addition, for many years he was a Visiting Professor at the UC Berkeley School of Law and also taught at the UCLA School of Law.<span>&amp;#160;</span><span></span></p><p>He received a bachelor's degree in history from the University of California at Berkeley and his J.D. from Yale, where he served as an articles Editor for the<em>Yale Law Journal</em>. Upon graduating from law school in 1988, Professor Amar clerked for Judge William A. Norris of the United States Court of Appeals for the Ninth Circuit, and then for Justice Harry A. Blackmun of the United States Supreme Court. After that he spent a few years at Gibson, Dunn&amp; Crutcher, devoting half of his time to federal white-collar criminal defense and the other half to complex civil litigation.<span></span><span></span></p><p>Professor Amar writes, teaches and consults in the public law fields, especially constitutional law, civil procedure, and remedies. He is a co-author (along with William Cohen and Jonathan Varat) of<em>Constitutional Law: Cases and Materials</em>(Foundation Press, 13th ed. 2009), and is a co-author on a number of volumes of the Wright&amp; Miller<em>Federal Practice and Procedure Treatise</em>(West Publishing Co.). He has published in a variety of journals, including the<em>Yale Law Journal</em>, the<em>Stanford Law Review</em>, the<em>Cornell Law Review</em>, the<em>Virginia Law Review</em>, the<em>Vanderbilt Law Review</em>, the<em>California Law Review</em>, the<em>Georgetown Law Journal</em>, the<em>UC Davis Law Review</em>, the<em>Emory Law Journal</em>, the<em>William and Mary Law Review</em>, the<em>Boston College Law Review</em>,<em>Constitutional Commentary</em>, the<em>Green Bag Journal</em>, the<em>Hastings Law Journal</em>, and the<em>Hastings Constitutional Law Quarterly</em>.<span></span><span></span></p><p>He authors a bi-weekly column on constitutional matters for&amp;#160;<a href=\"http://justia.com/\" target=\"_blank\">justia.com</a>, one of the most visited websites devoted to legal issues.&amp;#160; (For a decade he authored a similar column for&amp;#160;<a href=\"http://findlaw.com/\" target=\"_blank\">findlaw.com</a>) He is a frequent commentator on local and national radio and TV, and has written dozens of op-ed pieces for newspapers and magazines. He is a member of the American Law Institute.</p>","type":"text"
																					}
																				},
																				"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
																			},
																			{
																				"assetType":{},"blockId":{},"blockPath":{},
																				"fileId":{},"filePath":{},"identifier":"interests",
																				"pageId":{},"pagePath":{},"recycled":"false",
																				"structuredDataNodes":{
																					"structuredDataNode":
																						[
																							{
																								"assetType":{},"blockId":{},"blockPath":{},
																								"fileId":{},"filePath":{},"identifier":"interest",
																								"pageId":{},"pagePath":{},"recycled":"false",
																								"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																								"text":"Constitutional Law","type":"text"
																							},
																							{
																								"assetType":{},"blockId":{},"blockPath":{},
																								"fileId":{},"filePath":{},"identifier":"interest",
																								"pageId":{},"pagePath":{},"recycled":"false",
																								"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																								"text":"Civil Procedure (Including Civil Litigation And Complex Litigation)","type":"text"
																							},
																							{
																								"assetType":{},"blockId":{},"blockPath":{},
																								"fileId":{},"filePath":{},"identifier":"interest",
																								"pageId":{},"pagePath":{},"recycled":"false",
																								"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																								"text":"Criminal Law And Procedure","type":"text"
																							},
																							{
																								"assetType":{},"blockId":{},"blockPath":{},
																								"fileId":{},"filePath":{},"identifier":"interest",
																								"pageId":{},"pagePath":{},"recycled":"false",
																								"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																								"text":"Remedies","type":"text"
																							},
																							{
																								"assetType":{},"blockId":{},"blockPath":{},
																								"fileId":{},"filePath":{},"identifier":"interest",
																								"pageId":{},"pagePath":{},"recycled":"false",
																								"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																								"text":"Appellate Advocacy","type":"text"
																							}
																						]
																					},
																					"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
																				},
																				{
																					"assetType":{},"blockId":{},"blockPath":{},"fileId":{},"filePath":{},"identifier":"courses",
																					"pageId":{},"pagePath":{},"recycled":"false","structuredDataNodes":{
																						"structuredDataNode":{
																							"assetType":{},"blockId":{},"blockPath":{},
																							"fileId":{},"filePath":{},"identifier":"course",
																							"pageId":{},"pagePath":{},"recycled":"false",
																							"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																							"text":{},"type":"text"
																						}
																					},
																					"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
																				},
																				{
																					"assetType":{},"blockId":{},"blockPath":{},
																					"fileId":{},"filePath":{},"identifier":"careerHighlights",
																					"pageId":{},"pagePath":{},"recycled":"false",
																					"structuredDataNodes":{
																						"structuredDataNode":
																							[
																								{
																									"assetType":{},"blockId":{},"blockPath":{},
																									"fileId":{},"filePath":{},"identifier":"careerHighlight",
																									"pageId":{},"pagePath":{},"recycled":"false",
																									"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																									"text":"Has Taught at UC Davis, UC Berkeley, UCLA, and UC Hastings Law Schools","type":"text"
																								},
																								{
																									"assetType":{},"blockId":{},"blockPath":{},"fileId":{},"filePath":{},"identifier":"careerHighlight",
																									"pageId":{},"pagePath":{},"recycled":"false",
																									"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																									"text":"Served as a Law Clerk to U.S. Supreme Court Justice Harry Blackmun","type":"text"
																								},
																								{
																									"assetType":{},"blockId":{},"blockPath":{},"fileId":{},"filePath":{},"identifier":"careerHighlight",
																									"pageId":{},"pagePath":{},"recycled":"false",
																									"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																									"text":"Joined the Cohen and Varat Constitutional Law Casebook in 2003","type":"text"
																								},
																								{
																									"assetType":{},"blockId":{},"blockPath":{},"fileId":{},"filePath":{},"identifier":"careerHighlight",
																									"pageId":{},"pagePath":{},"recycled":"false","structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																									"text":"Appointed Associate Dean on July 1, 2008","type":"text"
																								},
																								{
																									"assetType":{},"blockId":{},"blockPath":{},"fileId":{},"filePath":{},"identifier":"careerHighlight",
																									"pageId":{},"pagePath":{},"recycled":"false","structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																									"text":"Has written biweekly online column since 2001","type":"text"
																								},
																								{
																									"assetType":{},"blockId":{},"blockPath":{},"fileId":{},"filePath":{},"identifier":"careerHighlight",
																									"pageId":{},"pagePath":{},"recycled":"false","structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																									"text":"Joined the Wright&Miller Federal Practice Treatise in 2000","type":"text"
																								},
																								{
																									"assetType":{},"blockId":{},"blockPath":{},"fileId":{},"filePath":{},"identifier":"careerHighlight",
																									"pageId":{},"pagePath":{},"recycled":"false","structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																									"text":"Received the ACLU of Southern California Distinguished Professor Award in 1997","type":"text"
																								},
																								{
																									"assetType":{},"blockId":{},"blockPath":{},"fileId":{},"filePath":{},"identifier":"careerHighlight",
																									"pageId":{},"pagePath":{},"recycled":"false","structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																									"text":"Practiced at Gibson, Dunn&Crutcher","type":"text"
																								},
																								{
																									"assetType":{},"blockId":{},"blockPath":{},"fileId":{},"filePath":{},"identifier":"careerHighlight",
																									"pageId":{},"pagePath":{},"recycled":"false","structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																									"text":"Served as an Articles Editor for the Yale Law Journal","type":"text"
																								}
																							]
																						},
																						"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
																					},
																					{
																						"assetType":{},"blockId":{},"blockPath":{},
																						"fileId":{},"filePath":{},"identifier":"activities",
																						"pageId":{},"pagePath":{},"recycled":"false",
																						"structuredDataNodes":{
																							"structuredDataNode":
																								[
																									{
																										"assetType":{},"blockId":{},"blockPath":{},
																										"fileId":{},"filePath":{},"identifier":"presentOrder",
																										"pageId":{},"pagePath":{},"recycled":"false",
																										"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																										"text":"1","type":"text"
																									},
																									{
																										"assetType":{},"blockId":{},"blockPath":{},
																										"fileId":{},"filePath":{},"identifier":"present",
																										"pageId":{},"pagePath":{},"recycled":"false",
																										"structuredDataNodes":{},
																										"symlinkId":{},"symlinkPath":{},
																										"text":{},"type":"text"
																									},
																									{
																										"assetType":{},"blockId":{},"blockPath":{},
																										"fileId":{},"filePath":{},"identifier":"projectOrder",
																										"pageId":{},"pagePath":{},"recycled":"false",
																										"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																										"text":"2","type":"text"
																									},
																									{
																										"assetType":{},"blockId":{},"blockPath":{},
																										"fileId":{},"filePath":{},"identifier":"projects",
																										"pageId":{},"pagePath":{},"recycled":"false",
																										"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																										"text":{},"type":"text"
																									},
																									{
																										"assetType":{},"blockId":{},"blockPath":{},
																										"fileId":{},"filePath":{},"identifier":"serviceOrder",
																										"pageId":{},"pagePath":{},"recycled":"false",
																										"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																										"text":"3","type":"text"
																									},
																									{
																										"assetType":{},"blockId":{},"blockPath":{},
																										"fileId":{},"filePath":{},"identifier":"service",
																										"pageId":{},"pagePath":{},"recycled":"false",
																										"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																										"text":{},"type":"text"
																									}
																								]
																							},
																							"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
																						},
																						{
																							"assetType":{},"blockId":{},"blockPath":{},
																							"fileId":{},"filePath":{},"identifier":"headshot",
																							"pageId":{},"pagePath":{},"recycled":"false",
																							"structuredDataNodes":{
																								"structuredDataNode":
																									[
																										{
																											"assetType":"file","blockId":{},"blockPath":{},
																											"fileId":"f6e933eea9ed9fa848a6a5dc676ae723",
																											"filePath":"images/people/n/amar-vikram.jpg","identifier":"photo",
																											"pageId":{},"pagePath":{},"recycled":"false",
																											"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																											"text":{},"type":"asset"
																										},
																										{
																											"assetType":"file","blockId":{},"blockPath":{},
																											"fileId":"fd4d526ba9ed9fa8216891f0aa3c7654",
																											"filePath":"images/people/h/amar-vikram.jpg",
																											"identifier":"headshot","pageId":{},"pagePath":{},
																											"recycled":"false","structuredDataNodes":{},"symlinkId":{},
																											"symlinkPath":{},"text":{},"type":"asset"
																										},
																										{
																											"assetType":"file","blockId":{},"blockPath":{},
																											"fileId":"9596f1dca9ed463001c8c0e618f327e3",
																											"filePath":"images/faculty/f/vikram-amar.jpg","identifier":"large",
																											"pageId":{},"pagePath":{},"recycled":"false",
																											"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																											"text":{},"type":"asset"
																										},
																										{
																											"assetType":"file","blockId":{},"blockPath":{},
																											"fileId":"95972c27a9ed463001c8c0e659ca6073",
																											"filePath":"images/faculty/t/vikram-amar.jpg","identifier":"thumb",
																											"pageId":{},"pagePath":{},"recycled":"false",
																											"structuredDataNodes":{},"symlinkId":{},"symlinkPath":{},
																											"text":{},"type":"asset"
																										}
																									]
																								},
																								"symlinkId":{},"symlinkPath":{},"text":{},"type":"group"
																							}
																						]
																					}
																				},
																				"xhtml":{}
																			},
																			"pageConfigurationSet":{},
																			"pageConfigurationSetContainer":{},
																			"publishSet":{},"publishSetContainer":{},"reference":{},"role":{},"scriptFormat":{},
																			"site":{},"siteDestinationContainer":{},"symlink":{},"target":{},"template":{},"textBlock":{},
																			"transportContainer":{},"twitterConnector":{},"twitterFeedBlock":{},"user":{},
																			"wordPressConnector":{},"workflowConfiguration":{},"workflowDefinition":{},
																			"workflowDefinitionContainer":{},"xhtmlDataDefinitionBlock":{},"xmlBlock":{},"xsltFormat":{}
																		};
  });
